# Read the Docs configuration file for EasyBite projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, EasyBite version, and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    dotnet: ">=4.6"
    # Add any other tools if needed

# Build documentation in the "docs/" directory
# Customize this path based on your project's structure
easybite:
  configuration: docs/easybite-config.yaml
  # You can customize EasyBite build settings here

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  # - epub
